<a href="https://colab.research.google.com/github/namgiju/mlprog/blob/main/car_evaluation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Car Evaluation 차량 등급 분류

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

## 1. 라이브러리 불러오기

In [3]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier

## 2. 구글 드라이브 연결

In [4]:
from google.colab import drive
drive.mount("/content/drive")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

## 3. 데이터 불러오기

In [5]:
df = pd.read_csv("/content/drive/MyDrive/car.data", header=None)
df.columns = ["buying", "maint", "doors", "persons", "lug_boot", "safety", "class"]
display(df.head(10))
print("데이터 크기:", df.shape)

  buying  maint doors persons lug_boot safety  class
0  vhigh  vhigh     2       2    small    low  unacc
1  vhigh  vhigh     2       2    small    med  unacc
2  vhigh  vhigh     2       2    small   high  unacc
3  vhigh  vhigh     2       2      med    low  unacc
4  vhigh  vhigh     2       2      med    med  unacc
5  vhigh  vhigh     2       2      med   high  unacc
6  vhigh  vhigh     2       2      big    low  unacc
7  vhigh  vhigh     2       2      big    med  unacc
8  vhigh  vhigh     2       2      big   high  unacc
9  vhigh  vhigh     2       4    small    low  unacc

데이터 크기: (1728, 7)

## 4. 라벨 인코딩

In [6]:
le = LabelEncoder()
df['buying'] = le.fit_transform(df['buying'])
df['maint'] = le.fit_transform(df['maint'])
df['doors'] = le.fit_transform(df['doors'])
df['persons'] = le.fit_transform(df['persons'])
df['lug_boot'] = le.fit_transform(df['lug_boot'])
df['safety'] = le.fit_transform(df['safety'])
df['class'] = le.fit_transform(df['class'])
display(df.head(10))

   buying  maint  doors  persons  lug_boot  safety  class
0       3      3      0        0         2       1      2
1       3      3      0        0         2       2      2
2       3      3      0        0         2       0      2
3       3      3      0        0         1       1      2
4       3      3      0        0         1       2      2
5       3      3      0        0         1       0      2
6       3      3      0        0         0       1      2
7       3      3      0        0         0       2      2
8       3      3      0        0         0       0      2
9       3      3      0        1         2       1      2

## 5. 피처/레이블 분리 및 데이터 분할

In [7]:
X = df.drop("class", axis=1)
y = df["class"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)
print("학습 데이터:", X_train.shape)
print("테스트 데이터:", X_test.shape)

학습 데이터: (1382, 6)
테스트 데이터: (346, 6)

## 6. 평가 함수 정의

In [8]:
results = []

def evaluate(name, model):
    model.fit(X_train, y_train)
    pred = model.predict(X_test)
    acc = accuracy_score(y_test, pred)
    results.append({"Model": name, "Accuracy (%)": round(acc * 100, 2)})
    print(f"--- {name} ---")
    print("Accuracy:", round(acc, 4))
    print(confusion_matrix(y_test, pred))
    print(classification_report(y_test, pred, zero_division=0))

## 7. Decision Tree

In [9]:
evaluate("Decision Tree", DecisionTreeClassifier(random_state=0))

--- Decision Tree ---
Accuracy: 0.9682
[[ 71   4   4   0]
 [  0  17   0   0]
 [  2   0 238   0]
 [  1   0   0   9]]
              precision    recall  f1-score   support

           0       0.96      0.90      0.93        79
           1       0.81      1.00      0.89        17
           2       0.98      0.99      0.99       240
           3       1.00      0.90      0.95        10

    accuracy                           0.97       346
   macro avg       0.94      0.95      0.94       346
weighted avg       0.97      0.97      0.97       346

## 8. Random Forest

In [10]:
evaluate("Random Forest", RandomForestClassifier(random_state=0))

--- Random Forest ---
Accuracy: 0.9653
[[ 73   4   1   1]
 [  2  13   0   2]
 [  1   0 239   0]
 [  1   0   0   9]]
              precision    recall  f1-score   support

           0       0.95      0.92      0.94        79
           1       0.76      0.76      0.76        17
           2       1.00      1.00      1.00       240
           3       0.75      0.90      0.82        10

    accuracy                           0.97       346
   macro avg       0.86      0.90      0.88       346
weighted avg       0.97      0.97      0.97       346

## 9. Logistic Regression

In [11]:
evaluate("Logistic Regression", LogisticRegression(max_iter=1000))

--- Logistic Regression ---
Accuracy: 0.6503
[[  9   0  67   3]
 [  1   0  16   0]
 [ 22   0 214   4]
 [  2   0   6   2]]
              precision    recall  f1-score   support

           0       0.26      0.11      0.16        79
           1       0.00      0.00      0.00        17
           2       0.71      0.89      0.79       240
           3       0.22      0.20      0.21        10

    accuracy                           0.65       346
   macro avg       0.30      0.30      0.29       346
weighted avg       0.56      0.65      0.59       346

## 10. KNN

In [12]:
evaluate("KNN", KNeighborsClassifier(n_neighbors=5))

--- KNN ---
Accuracy: 0.9046
[[ 60   2  17   0]
 [  5   8   3   1]
 [  3   0 237   0]
 [  1   0   1   8]]
              precision    recall  f1-score   support

           0       0.87      0.76      0.81        79
           1       0.80      0.47      0.59        17
           2       0.92      0.99      0.95       240
           3       0.89      0.80      0.84        10

    accuracy                           0.90       346
   macro avg       0.87      0.75      0.80       346
weighted avg       0.90      0.90      0.90       346

## 11. 결과 비교

In [13]:
result_df = pd.DataFrame(results).sort_values("Accuracy (%)", ascending=False).reset_index(drop=True)
result_df.index = result_df.index + 1
display(result_df)

                 Model  Accuracy (%)
1        Decision Tree         96.82
2        Random Forest         96.53
3                  KNN         90.46
4  Logistic Regression         65.03